[Unit]
After=
Wants=
Requires=
After=postgresql.service network-online.target
Requires=postgresql.service
Wants=network-online.target

[Service]
LoadCredential=marking-keyring:/etc/getomerch/credentials/marking-keyring.json
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
IPAddressDeny=
