[Unit]
After=pcscd.service
Wants=pcscd.service

[Service]
LoadCredential=marking-signer-clients:/etc/getomerch/credentials/marking-signer-clients.json
LoadCredential=marking-signer-certificate:/etc/getomerch/credentials/marking-signer-certificate.json
