BEGIN;
SET search_path = public, pg_catalog;
ALTER TABLE ONLY public.merch_warehouses ADD CONSTRAINT merch_warehouses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_product_categories ADD CONSTRAINT merch_product_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_fabric_types ADD CONSTRAINT merch_fabric_types_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_colors ADD CONSTRAINT merch_colors_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_sizes ADD CONSTRAINT merch_sizes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_designs ADD CONSTRAINT merch_designs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_decoration_types ADD CONSTRAINT merch_decoration_types_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_inventory ADD CONSTRAINT merch_inventory_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_print_inventory ADD CONSTRAINT merch_print_inventory_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_workshop_orders ADD CONSTRAINT merch_workshop_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_ozon_orders ADD CONSTRAINT merch_ozon_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_ozon_order_items ADD CONSTRAINT merch_ozon_order_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_ozon_finance_operations ADD CONSTRAINT merch_ozon_finance_operations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_expense_categories ADD CONSTRAINT merch_expense_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_expenses ADD CONSTRAINT merch_expenses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_ozon_import_runs ADD CONSTRAINT merch_ozon_import_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_ozon_import_items ADD CONSTRAINT merch_ozon_import_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.merch_product_categories ADD CONSTRAINT merch_product_categories_name_key UNIQUE (name);
ALTER TABLE ONLY public.merch_product_categories ADD CONSTRAINT merch_product_categories_slug_key UNIQUE (slug);
ALTER TABLE ONLY public.merch_fabric_types ADD CONSTRAINT merch_fabric_types_name_key UNIQUE (name);
ALTER TABLE ONLY public.merch_fabric_types ADD CONSTRAINT merch_fabric_types_slug_key UNIQUE (slug);
ALTER TABLE ONLY public.merch_colors ADD CONSTRAINT merch_colors_name_key UNIQUE (name);
ALTER TABLE ONLY public.merch_sizes ADD CONSTRAINT merch_sizes_name_key UNIQUE (name);
ALTER TABLE ONLY public.merch_decoration_types ADD CONSTRAINT merch_decoration_types_name_key UNIQUE (name);
ALTER TABLE ONLY public.merch_decoration_types ADD CONSTRAINT merch_decoration_types_slug_key UNIQUE (slug);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_sku_key UNIQUE (sku);
ALTER TABLE ONLY public.merch_inventory ADD CONSTRAINT merch_inventory_product_id_warehouse_id_key UNIQUE (product_id, warehouse_id);
ALTER TABLE ONLY public.merch_print_inventory ADD CONSTRAINT merch_print_inventory_design_id_warehouse_id_key UNIQUE (design_id, warehouse_id);
ALTER TABLE ONLY public.merch_workshop_orders ADD CONSTRAINT merch_workshop_orders_order_number_key UNIQUE (order_number);
ALTER TABLE ONLY public.merch_ozon_orders ADD CONSTRAINT merch_ozon_orders_posting_number_key UNIQUE (posting_number);
ALTER TABLE ONLY public.merch_ozon_finance_operations ADD CONSTRAINT merch_ozon_finance_operations_operation_id_key UNIQUE (operation_id);
ALTER TABLE ONLY public.merch_warehouses ADD CONSTRAINT merch_warehouses_type_check CHECK (type = ANY (ARRAY['own'::text, 'workshop'::text]));
ALTER TABLE ONLY public.merch_designs ADD CONSTRAINT merch_designs_type_check CHECK (type = ANY (ARRAY['print'::text, 'embroidery'::text]));
ALTER TABLE ONLY public.merch_decoration_types ADD CONSTRAINT merch_decoration_types_made_at_check CHECK (made_at = ANY (ARRAY['own'::text, 'workshop'::text]));
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT design_decoration_consistency CHECK (is_blank = true AND design_id IS NULL AND decoration_type_id IS NULL OR is_blank = false AND design_id IS NOT NULL AND decoration_type_id IS NOT NULL);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_hoodie_fabric_chk CHECK (hoodie_fabric IS NULL OR (hoodie_fabric = ANY (ARRAY['FLC'::text, 'NF'::text])));
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_hoodie_fit_chk CHECK (hoodie_fit IS NULL OR (hoodie_fit = ANY (ARRAY['REG'::text, 'CRP'::text])));
ALTER TABLE ONLY public.merch_inventory ADD CONSTRAINT merch_inventory_quantity_check CHECK (quantity >= 0);
ALTER TABLE ONLY public.merch_print_inventory ADD CONSTRAINT merch_print_inventory_quantity_check CHECK (quantity >= 0);
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_quantity_check CHECK (quantity > 0);
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_type_check CHECK (type = ANY (ARRAY['receive'::text, 'transfer'::text, 'sale'::text, 'production'::text, 'adjustment'::text, 'writeoff'::text]));
ALTER TABLE ONLY public.merch_workshop_orders ADD CONSTRAINT merch_workshop_orders_status_check CHECK (status = ANY (ARRAY['sent'::text, 'ready'::text, 'received'::text, 'cancelled'::text]));
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_quantity_check CHECK (quantity > 0);
ALTER TABLE ONLY public.merch_expenses ADD CONSTRAINT merch_expenses_amount_check CHECK (amount > 0::numeric);
ALTER TABLE ONLY public.merch_ozon_import_runs ADD CONSTRAINT merch_ozon_import_runs_status_check CHECK (status = ANY (ARRAY['preview'::text, 'applying'::text, 'applied'::text, 'partial'::text, 'failed'::text]));
ALTER TABLE ONLY public.merch_ozon_import_items ADD CONSTRAINT merch_ozon_import_items_severity_check CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text]));
ALTER TABLE ONLY public.merch_ozon_import_items ADD CONSTRAINT merch_ozon_import_items_status_check CHECK (status = ANY (ARRAY['new_design'::text, 'new_product'::text, 'update'::text, 'noop'::text, 'conflict'::text, 'skipped'::text, 'applied'::text, 'error'::text]));
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_category_id_fkey FOREIGN KEY (category_id) REFERENCES merch_product_categories(id);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_color_id_fkey FOREIGN KEY (color_id) REFERENCES merch_colors(id);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_decoration_type_id_fkey FOREIGN KEY (decoration_type_id) REFERENCES merch_decoration_types(id);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_design_id_fkey FOREIGN KEY (design_id) REFERENCES merch_designs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_fabric_id_fkey FOREIGN KEY (fabric_id) REFERENCES merch_fabric_types(id);
ALTER TABLE ONLY public.merch_products ADD CONSTRAINT merch_products_size_id_fkey FOREIGN KEY (size_id) REFERENCES merch_sizes(id);
ALTER TABLE ONLY public.merch_inventory ADD CONSTRAINT merch_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES merch_products(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_inventory ADD CONSTRAINT merch_inventory_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES merch_warehouses(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_print_inventory ADD CONSTRAINT merch_print_inventory_design_id_fkey FOREIGN KEY (design_id) REFERENCES merch_designs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_print_inventory ADD CONSTRAINT merch_print_inventory_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES merch_warehouses(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_design_id_fkey FOREIGN KEY (design_id) REFERENCES merch_designs(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_from_warehouse_id_fkey FOREIGN KEY (from_warehouse_id) REFERENCES merch_warehouses(id);
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES merch_products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_source_design_id_fkey FOREIGN KEY (source_design_id) REFERENCES merch_designs(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_source_product_id_fkey FOREIGN KEY (source_product_id) REFERENCES merch_products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_to_warehouse_id_fkey FOREIGN KEY (to_warehouse_id) REFERENCES merch_warehouses(id);
ALTER TABLE ONLY public.merch_transactions ADD CONSTRAINT merch_transactions_workshop_order_id_fkey FOREIGN KEY (workshop_order_id) REFERENCES merch_workshop_orders(id);
ALTER TABLE ONLY public.merch_workshop_orders ADD CONSTRAINT merch_workshop_orders_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES merch_warehouses(id);
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_blank_product_id_fkey FOREIGN KEY (blank_product_id) REFERENCES merch_products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_decoration_type_id_fkey FOREIGN KEY (decoration_type_id) REFERENCES merch_decoration_types(id);
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_design_id_fkey FOREIGN KEY (design_id) REFERENCES merch_designs(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES merch_workshop_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_workshop_order_items ADD CONSTRAINT merch_workshop_order_items_result_product_id_fkey FOREIGN KEY (result_product_id) REFERENCES merch_products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_ozon_orders ADD CONSTRAINT merch_ozon_orders_shipped_from_warehouse_id_fkey FOREIGN KEY (shipped_from_warehouse_id) REFERENCES merch_warehouses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_ozon_orders ADD CONSTRAINT merch_ozon_orders_workshop_order_id_fkey FOREIGN KEY (workshop_order_id) REFERENCES merch_workshop_orders(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_ozon_order_items ADD CONSTRAINT merch_ozon_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES merch_ozon_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_ozon_order_items ADD CONSTRAINT merch_ozon_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES merch_products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_ozon_order_items ADD CONSTRAINT merch_ozon_order_items_shipped_from_warehouse_id_fkey FOREIGN KEY (shipped_from_warehouse_id) REFERENCES merch_warehouses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_expenses ADD CONSTRAINT merch_expenses_category_id_fkey FOREIGN KEY (category_id) REFERENCES merch_expense_categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.merch_ozon_import_items ADD CONSTRAINT merch_ozon_import_items_run_id_fkey FOREIGN KEY (run_id) REFERENCES merch_ozon_import_runs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.merch_ozon_import_items ADD CONSTRAINT merch_ozon_import_items_target_product_id_fkey FOREIGN KEY (target_product_id) REFERENCES merch_products(id) ON DELETE SET NULL;
CREATE INDEX merch_designs_code_idx ON public.merch_designs USING btree (code) WHERE (code IS NOT NULL);
CREATE UNIQUE INDEX merch_designs_code_type_unique ON public.merch_designs USING btree (code, type) WHERE (code IS NOT NULL);
CREATE UNIQUE INDEX idx_merch_products_blank_combo ON public.merch_products USING btree (category_id, fabric_id, color_id, size_id) WHERE (is_blank = true);
CREATE INDEX idx_merch_products_finished_combo ON public.merch_products USING btree (category_id, fabric_id, color_id, size_id, design_id, decoration_type_id) WHERE (is_blank = false);
CREATE INDEX merch_products_legacy_skus_gin ON public.merch_products USING gin (legacy_skus);
CREATE UNIQUE INDEX merch_products_ozon_sku_key ON public.merch_products USING btree (ozon_sku) WHERE (ozon_sku IS NOT NULL);
CREATE INDEX idx_inventory_product ON public.merch_inventory USING btree (product_id);
CREATE INDEX idx_inventory_warehouse ON public.merch_inventory USING btree (warehouse_id);
CREATE INDEX merch_print_inventory_design_idx ON public.merch_print_inventory USING btree (design_id);
CREATE INDEX merch_print_inventory_warehouse_idx ON public.merch_print_inventory USING btree (warehouse_id);
CREATE INDEX idx_transactions_date ON public.merch_transactions USING btree (occurred_at DESC);
CREATE INDEX idx_transactions_product ON public.merch_transactions USING btree (product_id);
CREATE INDEX idx_workshop_items_order ON public.merch_workshop_order_items USING btree (order_id);
CREATE INDEX merch_ozon_orders_created_idx ON public.merch_ozon_orders USING btree (ozon_created_at DESC);
CREATE INDEX merch_ozon_orders_shipped_idx ON public.merch_ozon_orders USING btree (shipped_at);
CREATE INDEX merch_ozon_orders_source_idx ON public.merch_ozon_orders USING btree (source);
CREATE INDEX merch_ozon_orders_status_idx ON public.merch_ozon_orders USING btree (status);
CREATE INDEX merch_ozon_orders_workshop_order_idx ON public.merch_ozon_orders USING btree (workshop_order_id);
CREATE INDEX merch_ozon_order_items_offer_idx ON public.merch_ozon_order_items USING btree (offer_id);
CREATE INDEX merch_ozon_order_items_order_idx ON public.merch_ozon_order_items USING btree (order_id);
CREATE INDEX merch_ozon_order_items_product_idx ON public.merch_ozon_order_items USING btree (product_id);
CREATE INDEX merch_ozon_finance_ops_date_idx ON public.merch_ozon_finance_operations USING btree (operation_date DESC);
CREATE INDEX merch_ozon_finance_ops_posting_idx ON public.merch_ozon_finance_operations USING btree (posting_number);
CREATE INDEX merch_ozon_finance_ops_type_idx ON public.merch_ozon_finance_operations USING btree (operation_type);
CREATE INDEX merch_expenses_category_idx ON public.merch_expenses USING btree (category_id);
CREATE INDEX merch_expenses_occurred_idx ON public.merch_expenses USING btree (occurred_at DESC);
CREATE INDEX merch_ozon_import_runs_created_idx ON public.merch_ozon_import_runs USING btree (created_at DESC);
CREATE INDEX merch_ozon_import_items_offer_idx ON public.merch_ozon_import_items USING btree (offer_id);
CREATE INDEX merch_ozon_import_items_run_idx ON public.merch_ozon_import_items USING btree (run_id);
CREATE UNIQUE INDEX merch_ozon_import_items_run_offer_key ON public.merch_ozon_import_items USING btree (run_id, offer_id);
CREATE INDEX merch_ozon_import_items_status_idx ON public.merch_ozon_import_items USING btree (status);
CREATE TRIGGER trg_inventory_updated_at BEFORE UPDATE ON merch_inventory FOR EACH ROW EXECUTE FUNCTION update_inventory_timestamp();
COMMIT;
